name: Build
on:
  workflow_call:
    inputs:
      image:
        description: Image to build
        required: true
        type: string
      artifact-name:
        description: Artifact name of build dir
        required: false
        type: string
        default: 'build'
      cmake-preset:
        description: Specify CMake preset to use
        required: false
        type: string
        default: ''
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
    env:
      cmake-preset: ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/actions/dep-artifacts
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir build
      - name: Set CMake preset
        if: ${{ inputs.cmake-preset != '' }}
        run: echo "cmake-preset=--preset ${{ inputs.cmake-preset }}" >> $GITHUB_ENV
      - name: Configure
        run: cmake ${{ env.cmake-preset }} -S . -B build
      - name: Build
        run: cmake --build build
      - name: Tar artifact (keep permissions)
        run: tar -czf build-dir.tar build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: build-dir.tar
          retention-days: 1
