name: Weekly Project Rebuild
on:
  schedule:
    - cron: '0 4 * * 4'
jobs:
  build:
    if: github.repository == 'winft/como'
    uses: ./.github/workflows/build.yml
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/kwinft-base-master

  package:
    uses: ./.github/workflows/package.yml
    needs: build
    with:
      image: registry.gitlab.com/kwinft/ci-images/archlinux/kwinft-base-master
      package-name: como
